Algoritmo "Res_Terreno"

Var

    larg, comp, valorM, areaT, precoT : real
Inicio

    // Corrigido
    escreva("Digite a largura do terreno: ")
    leia(larg)
    escreva("Digite o comprimento do terreno: ")
    leia(comp)
    escreva("Digite o valor do metro do terreno: ")
    leia(valorM)
    
    areaT <- larg * comp;
    precoT <- areaT * ValorM
    
    escreval("Area do terreno = ", areaT:5:2)
    escreval("Preco do terreno = ", precoT:5:2)

Fimalgoritmo